import { Link } from "react-router-dom";

const TermsOfService = () => {
    return (
        <div className="min-h-screen bg-background">
            <div className="container mx-auto px-4 py-16 max-w-4xl">

                {/* English */}
                <section className="mb-16">
                    <h1 className="text-4xl font-bold mb-2 text-foreground">Terms of Service</h1>
                    <p className="text-sm text-muted-foreground mb-8">Last updated: February 2026</p>

                    <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground">
                        <section>
                            <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                By accessing or using Calor X ("the App", "the Service"), you agree to be bound by these Terms of Service
                                and our Privacy Policy. If you do not agree, please do not use the App.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">2. Description of Service</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Calor X is an AI-powered nutrition tracking application that analyses food photographs and provides
                                estimated nutritional information. The App is designed for general wellness purposes and is <strong className="text-foreground">not</strong> a
                                medical device or substitute for professional medical advice.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">3. User Accounts</h2>
                            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                                <li>You must be at least 13 years old to create an account.</li>
                                <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                                <li>You agree to provide accurate and up-to-date information during registration.</li>
                                <li>You are responsible for all activity that occurs under your account.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">4. AI Disclaimer</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Nutritional data provided by the App is generated by artificial intelligence and is an <strong className="text-foreground">estimate only</strong>.
                                Actual nutritional content may vary based on recipe, preparation method, portion size, and ingredients.
                                Do not rely solely on this App to manage any medical condition, allergy, or dietary requirement. Always
                                consult a qualified healthcare professional before making significant dietary changes.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">5. Acceptable Use</h2>
                            <p className="text-muted-foreground leading-relaxed mb-2">You agree not to:</p>
                            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                                <li>Use the App for any unlawful purpose.</li>
                                <li>Attempt to reverse-engineer, decompile, or hack the App.</li>
                                <li>Upload content that is illegal, offensive, or violates third-party rights.</li>
                                <li>Use automated tools to scrape or abuse the API.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">6. Subscriptions & Billing</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Calor X may offer free and paid subscription tiers. Paid subscriptions are billed in advance on a
                                monthly or annual basis. You may cancel at any time; cancellation takes effect at the end of the current
                                billing period. All sales are final unless required otherwise by applicable law.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">7. Intellectual Property</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                All content, design, code, and branding within the App are the property of Calor X and protected by
                                applicable intellectual property laws. You may not reproduce, distribute, or create derivative works
                                without prior written permission.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">8. Limitation of Liability</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                To the maximum extent permitted by law, Calor X shall not be liable for any indirect, incidental,
                                special, consequential, or punitive damages arising from your use of or inability to use the Service,
                                including any reliance on AI-generated nutritional data.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">9. Changes to Terms</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                We may update these Terms from time to time. We will notify you of material changes via email or
                                in-app notice. Continued use of the App after changes constitutes acceptance of the revised Terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">10. Contact</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                For any questions regarding these Terms:{" "}
                                <a href="mailto:support@calor-x.app" className="text-primary underline">
                                    support@calor-x.app
                                </a>
                            </p>
                        </section>
                    </div>
                </section>

                {/* Divider */}
                <hr className="border-border mb-16" />

                {/* Arabic */}
                <section dir="rtl" className="mb-16">
                    <h1 className="text-4xl font-bold mb-2 text-foreground">شروط الخدمة</h1>
                    <p className="text-sm text-muted-foreground mb-8">آخر تحديث: فبراير 2026</p>

                    <div className="space-y-8 text-foreground">
                        <section>
                            <h2 className="text-2xl font-semibold mb-3">1. قبول الشروط</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                باستخدامك لتطبيق كالور إكس ("التطبيق")، فإنك توافق على هذه الشروط وسياسة الخصوصية. إذا كنت لا توافق، يرجى عدم استخدام التطبيق.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">2. وصف الخدمة</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                كالور إكس هو تطبيق تتبع تغذية مدعوم بالذكاء الاصطناعي يحلل صور الطعام ويوفر معلومات غذائية تقريبية. التطبيق مخصص لأغراض الصحة العامة <strong className="text-foreground">وليس</strong> بديلاً عن الرعاية الصحية المتخصصة.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">3. حسابات المستخدمين</h2>
                            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                                <li>يجب أن يكون عمرك 13 عامًا على الأقل لإنشاء حساب.</li>
                                <li>أنت مسؤول عن الحفاظ على سرية بيانات دخولك.</li>
                                <li>أنت مسؤول عن جميع الأنشطة التي تحدث تحت حسابك.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">4. إخلاء مسؤولية الذكاء الاصطناعي</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                البيانات الغذائية المقدمة من التطبيق مُولَّدة بواسطة الذكاء الاصطناعي وهي <strong className="text-foreground">تقديرية فقط</strong>. لا تعتمد على التطبيق وحده لإدارة حالة طبية. استشر دائمًا مختصًا صحيًا مؤهلاً قبل إجراء تغييرات غذائية كبيرة.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">5. الاشتراكات والفواتير</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                قد يقدم كالور إكس خططًا مجانية ومدفوعة. يتم إصدار فواتير الاشتراكات المدفوعة مسبقًا على أساس شهري أو سنوي. يمكنك الإلغاء في أي وقت؛ ويسري الإلغاء في نهاية فترة الفوترة الحالية.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">6. تحديد المسؤولية</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                لن يكون كالور إكس مسؤولاً عن أي أضرار غير مباشرة أو عرضية ناجمة عن استخدامك للخدمة أو الاعتماد على البيانات الغذائية المُولَّدة بالذكاء الاصطناعي.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">7. التواصل</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                لأي استفسارات بشأن هذه الشروط:{" "}
                                <a href="mailto:support@calor-x.app" className="text-primary underline">
                                    support@calor-x.app
                                </a>
                            </p>
                        </section>
                    </div>
                </section>

                <div className="text-center">
                    <Link to="/" className="text-primary hover:underline text-sm">
                        ← Back to Home / العودة للرئيسية
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
