project_id = "lurcmwqvgjfsfzsmvkne"

[functions.analyze-food]
verify_jwt = false

[functions.coach]
verify_jwt = false

[functions.upgrade-admin]
enabled = true
verify_jwt = true
import_map = "./functions/upgrade-admin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upgrade-admin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upgrade-admin/*.html" ]
